### ISSUE TITLE
Could not initialize class javax.crypto.SunJCE_b error

### ISSUE THREAD

**Issue by bernaxa** [truebit/clang-scanbuild-plugin#1]
Hello,

We get this error with mvn 

mvn clean package -Dmaven.test.skip=true
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/jenkins-ci/tools/maven-hpi-plugin/1.74/maven-hpi-plugin-1.74.pom
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: Could not initialize class javax.crypto.SunJCE_b
        at javax.crypto.KeyGenerator.a(DashoA13_..)
        at javax.crypto.KeyGenerator.<init>(DashoA13_..)
        at javax.crypto.KeyGenerator.getInstance(DashoA13*..)
        at com.sun.net.ssl.internal.ssl.JsseJce.getKeyGenerator(JsseJce.java:223)
        at com.sun.net.ssl.internal.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:91)
        at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:747)
        at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:241)
        at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Handshaker.java:593)

**Comment by truebit** [comment]
I do not think it's the bug of this plugin. it is more like the incompatible Java version. Try use Java 6 to build it.
